from typing import Callable, Tuple
import torch
from torch.utils.data import DataLoader
from torch.utils.data.dataloader import default_collate

from .dataset_builder import CloudDataset


class ValidationDataloader(DataLoader):
    """
    Class that loads a validation dataset.
    """
    def __init__(
        self,
        dataset: CloudDataset,
        *args,
        n_past_frames=3,
        **kwargs
        ) -> None:
        """
        Initialize a ValidationDataloader.

        Parameters
        ----------
        dataset : CloudDataset
            The dataset used to create the dataloader.
        """
        self.n_past_frames = n_past_frames
        super().__init__(
            dataset,
            *args,
            collate_fn=lambda b: self._collate_fn(default_collate(b)),
            **kwargs)
        
    def _collate_fn(self, batch: torch.FloatTensor) -> Tuple[torch.FloatTensor, torch.FloatTensor]:
        #b, t, _, h, w = batch.shape
        # Get the past frames batch.
        past_frames_batch = batch[:,:self.n_past_frames]
        # Get the target frames batch considering just the first channel as it
        # is the only one to validate.
        target_frames_batch = batch[:,self.n_past_frames:, :1]
        return past_frames_batch, target_frames_batch

# TODO: check if nomenclature of noise parameter is correct
class NoisifyDataloader(DataLoader):
    """
    Class that noisifies the last frame of a dataloader by applying
    a noise function, after collating the batch.
    """
    def __init__(
        self,
        dataset: CloudDataset,
        *args,
        #noise_function: Callable[[torch.FloatTensor], torch.FloatTensor] = None,
        n_frames_to_nosify: int = 1,
        **kwargs
        ) -> None:
        """
        Initialize a NoisifyDataloader.

        Parameters
        ----------
        dataset : CloudDataset
            The dataset used to create the dataloader.
        n_frames_to_nosify: int, optional
            The number of last frames to nosify, by default 1.
        """
        noise_function = self.__get_nosify_ddpm()

        super().__init__(
            dataset,
            *args,
            collate_fn=self.__get_noisify_collate_fn(
                noise_function,
                n_frames_to_nosify),
            **kwargs)

    @staticmethod
    def __get_nosify_ddpm() -> Callable[[torch.FloatTensor], Tuple[torch.FloatTensor, torch.FloatTensor, torch.FloatTensor]]:
        """
        Get the default noise function.

        Returns
        -------
        (FloatTensor) -> (FloatTensor, FloatTensor, FloatTensor)
            The default noise function.
        """
        ## DDPM params
        ## From fastai V2 Course DDPM notebooks
        BETAMIN, BETAMAX, N_STEPS = .0001, .02, 1_000
        beta = torch.linspace(BETAMIN, BETAMAX, N_STEPS)
        alpha = 1. - beta
        alphabar = alpha.cumprod(dim=0)
        # TODO: not used?
        sigma = beta.sqrt()

        def _noisify_ddpm(x0: torch.FloatTensor) -> Tuple[torch.FloatTensor, torch.FloatTensor, torch.FloatTensor]:
            """
            The default noise function.

            Parameters
            ----------
            x0 : FloatTensor
                The last frame of a sequence of frames to be noisified.

            Returns
            -------
            FloatTensor
                The noisified last frame.
            FloatTensor
                The temperature of the noise.
            FloatTensor
                The entropy of the noise.
            """
            device = x0.device
            n = len(x0)
            t = torch.randint(0, N_STEPS, (n,), dtype=torch.long)
            ε = torch.randn(x0.shape, device=device)
            ᾱ_t = alphabar[t].reshape(-1, 1, 1, 1, 1).to(device)
            xt = ᾱ_t.sqrt() * x0 + (1-ᾱ_t).sqrt() * ε
            return xt, t.to(device), ε

        return _noisify_ddpm

    @staticmethod
    def __noisify_last_n_frames(
        frames: torch.FloatTensor,
        noise_function: Callable[[torch.FloatTensor], Tuple[torch.FloatTensor, torch.FloatTensor, torch.FloatTensor]],
        n_frames_to_nosify: int
        ) -> Tuple[torch.FloatTensor, torch.FloatTensor, torch.FloatTensor]:
        """
        Nosify the last frame of a sequence of frames. The noise is generated by
        the noise function. the temperature and entropy of the noise are also
        returned. The noise is concatenated to the sequence of previous frames.

        Parameters
        ----------
        frames : FloatTensor
            The sequence of frames of shape (B, T, C, H, W), where B is the batch
            size, T is the sequence length, C is the number of channels, H is the
            height and W is the width.
        noise_function : (FloatTensor) -> (FloatTensor, FloatTensor, FloatTensor)
            The function that generates the noise.

        Returns
        -------
        FloatTensor
            The sequence of frames with the noise concatenated to the last frame.
        FloatTensor
            The temperature of the noise.
        FloatTensor
            The entropy of the noise.
        """
        b, t, _, h, w = frames.shape
        past_frames = frames[:,:-n_frames_to_nosify]
        last_frame  = frames[:,-n_frames_to_nosify:]
        #past_frames = past_frames.reshape(b, -1, h, w) # reshape, timesteps reshaped to channels
        noise, t, e = noise_function(last_frame)
        #noise = noise.reshape(b, -1, h, w)
        noise_frames = torch.cat([past_frames, noise], dim=1)
        return noise_frames, t, e

    @staticmethod
    def __get_noisify_collate_fn(
        noise_function: Callable[[torch.FloatTensor], torch.FloatTensor],
        n_frames_to_nosify: int,
        ) -> Callable[[torch.FloatTensor], Tuple[torch.FloatTensor, torch.FloatTensor, torch.FloatTensor]]:
        """
        Get a collate function that noisifies the last frame of a batch and
        returns the temperature and entropy of the noise.

        Parameters
        ----------
        noise_function : (FloatTensor) -> (FloatTensor, FloatTensor, FloatTensor)
            The function that noisifies the last frame of a sequence and
            returns the temperature and entropy of the noise.

        Returns
        -------
        (FloatTensor) -> (FloatTensor, FloatTensor, FloatTensor)
            The collate function that noisifies the last frame of a batch and
            returns the temperature and entropy of the noise.
        """
        #def _inner(b):
        #    return noisify_last_frame(default_collate(b), noise_func)
        return lambda batch: NoisifyDataloader.__noisify_last_n_frames(
            default_collate(batch), noise_function, n_frames_to_nosify)
